### ISSUE TITLE
issue with composer require

### ISSUE THREAD

**Issue by PixelDog** [lrc/silverstripe-pseudo-cron#4]
Using SS 3.6 I tried:

composer require "lrc/silverstripe-pseudo-cron:*"

and get:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package lrc/silverstripe-pseudo-cron could not be found in any version, there may be a typo in the package name.

but it seems like it should work? Maybe the package is not registered, not sure how that works.

Thanks!

**Comment by Linkdup** [comment]
The package is not registered, you can just include it in your composer file by adding:

`"repositories": [{"type": "vcs","url": "https://github.com/lrc/silverstripe-link-field.git"}]`

Please note that this library has not been used for years, so it has not been tried on SS 3.6.

**Comment by drzax** [comment]
And feel free to submit a pull request @PixelDog. 

@Linkdup —should we add a license so anyone can fork or do anything else they want with it? I suggest MIT.

**Comment by Linkdup** [comment]
@drzax - done!

**Comment by PixelDog** [comment]
@Linkdup @drzax great thanks! Giving it a go with 3.6 :-)
